apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/codefresh/cap-app-proxy
  newName: dustinvanbuskirk/cap-app-proxy
  newTag: 1.1871.0

resources:
- github.com/codefresh-io/cli-v2/manifests/app-proxy?ref=v0.0.534
