apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/codefresh/argocli
  newName: dustinvanbuskirk/argocli
  newTag: v3.2.6-cap-CR-8697
- name: quay.io/codefresh/argoexec
  newName: dustinvanbuskirk/argoexec
  newTag: v3.2.6-cap-CR-8697
- name: quay.io/codefresh/workflow-controller
  newName: dustinvanbuskirk/workflow-controller
  newTag: v3.2.6-cap-CR-8697

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: workflow-controller
  patch: |
    - op: replace
      path: /spec/template/spec/containers/0/args/3
      value: dustinvanbuskirk/argoexec:v3.2.6-cap-CR-8697

resources:
- github.com/codefresh-io/csdp-official.git/csdp/hybrid/basic/apps/argo-workflows?ref=0.1.15
