apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/codefresh/argocli
  newName: dustinvanbuskirk/argocli
  newTag: v3.2.6-cap-CR-8697
- name: quay.io/codefresh/argoexec
  newName: dustinvanbuskirk/argoexec
  newTag: v3.2.6-cap-CR-8697
- name: quay.io/codefresh/workflow-controller
  newName: dustinvanbuskirk/workflow-controller
  newTag: v3.2.6-cap-CR-8697

resources:
- github.com/codefresh-io/cli-v2/manifests/argo-workflows?ref=v0.0.534
