apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/codefresh/argocd
  newName: dustinvanbuskirk/argocd
  newTag: v2.3.4-cap-CR-14359-app-uid
- name: ghcr.io/dexidp/dex
  newName: dustinvanbuskirk/dex
  newTag: v2.30.2
- name: quay.io/codefresh/redis
  newName: dustinvanbuskirk/redis
  newTag: 6.2.6-alpine
- name: quay.io/codefresh/applicationset
  newName: dustinvanbuskirk/applicationset
  newTag: latest

resources:
- github.com/codefresh-io/cli-v2/manifests/argo-cd?ref=v0.0.534
